.env, docker-compose.yaml, package.json, prisma/schema.prisma, src/app.controller.ts, src/app.module.ts, src/prisma/prisma.module.ts, src/prisma/prisma.service.ts, yarn.lock
- Prisma 초기화 및 임시 테이블(User) 생성
- Prisma Module 생성
- 로컬 개발용 PostgreSQL Docker compose 추가
- 관련 package.json script 추가
=> Prisma 및 로컬 개발용 DB 세팅

.github/labeler.yml
- `Document` label이 지속적으로 붙는 오류 수정
=> GH Action labeler 수정

package.json
=> chore: pnpm package manager

src/schema/folder.schema.ts, src/schema/post.schema.ts
=> fix: schema error type

src/common/decorators/getUser.decorator.ts
-`@GetUser` 데코레이터에서 id를 바로 반환하도록 변경
=> GetUser데코레이터에서 디폴트로 id필드 반환하도록 수정

.github/workflows/build.yml
- pnpm gh action args 수정
- `--frozen-lockfile` 추가
=> Chore: GH Action pnpm 옵션 수정

src/common/dto/index.ts, src/common/dto/pagination.dto.ts, src/common/index.ts
- Pagination을 위한 DTO와 Metadata DTO 추가했어용
=> Feat: PaginationQuery, PaginationMetadata dto 추가

src/modules/posts/docs/controller.docs.ts, src/modules/posts/docs/createPost.docs.ts, src/modules/posts/docs/deletePost.docs.ts, src/modules/posts/docs/listPost.docs.ts, src/modules/posts/posts.controller.ts, src/modules/posts/posts.repository.ts, src/modules/posts/posts.service.ts
- Delete Post API 추가 작성
- 각각의 Docs에 있는 Swagger Bearer Auth Controller level로 이관
=> Post Delete API 추가

src/modules/folders/folders.service.ts
=> Dev API Hotfix: folder create 오류 수정

src/infrastructure/aws-lambda/aws-lambda.service.ts
=> refactor: aws credentials apply

src/modules/posts/dto/find-in-folder.dto.ts
=> `/folder/:folderId/posts` Hotfix 

src/infrastructure/database/schema/post.schema.ts
=> hotfix: reatAt default value to null

src/modules/posts/posts.service.ts
=> Feature: Extract foldernames and send to lambda payload

src/ai_handler.ts, src/modules/posts/posts.repository.ts, src/modules/posts/posts.service.ts
> 기존 post 생성 시 id 리턴 추가
> ai-worker 람다에서 post id payload 추가
=> feature/ai-worker 

src/ai_handler.ts
> cloud-watch용 로그 추가
> 불필요한 로직 리팩토링
> 없음!
cloud-watch에서 앞으로 요약 결과 확인가능~
=> refactor: ai 요약 람다 서버 추가세팅

src/app.config.ts, src/common/filter/base.filter.ts, src/common/utils/createErrorObject.util.ts, src/common/utils/index.ts, src/modules/classification/classification.repository.ts, src/modules/classification/classification.service.ts, src/modules/classification/error/index.ts, src/modules/folders/docs/folder-api.docs.ts, src/modules/folders/error/index.ts, src/modules/folders/folders.repository.ts, src/modules/posts/docs/createPost.docs.ts, src/modules/posts/docs/deletePost.docs.ts, src/modules/posts/docs/updatePost.docs.ts, src/modules/posts/docs/updatePostFolder.docs.ts, src/modules/posts/dto/updatePost.dto.ts, src/modules/posts/error/index.ts, src/modules/posts/posts.controller.ts, src/modules/posts/posts.repository.ts, src/modules/posts/posts.service.ts
- 에러코드 object 생성 함수 추가
- 예외 필터 수정
- Post 예시 Error Code 생성
- Classification은 아직 적용 전입니다
=> 에러코드 체계 적용

src/modules/posts/posts.service.ts
- Post `findPostOrThrow` 호출 매개변수 수정
=> Fix: Fix post findPostOrThrow parameter error

src/modules/classification/classification.controller.ts, src/modules/classification/classification.repository.ts, src/modules/classification/classification.service.ts, src/modules/classification/docs/index.ts, src/modules/classification/docs/patchAIPostList.docs.ts, src/modules/classification/dto/classification.dto.ts, src/modules/posts/posts.repository.ts
=> Hotfix : ai classification 1개 이동 api 추가, ai 쪽 폴더 리스트에 '나중에 읽을 폴더'제하게 수정

src/modules/posts/response/listPost.response.ts
=> fix: 피드 전체 조회시 썸네일 이미지 URL 카멜케이스로 변경

src/modules/folders/docs/folder-api.docs.ts, src/modules/folders/folders.controller.ts, src/modules/folders/folders.repository.ts, src/modules/folders/folders.service.ts, src/modules/folders/responses/folder-list.response.ts, src/modules/folders/responses/post.response.ts, src/modules/posts/posts.controller.ts, src/modules/posts/posts.repository.ts, src/modules/posts/posts.service.ts
- Folder Update, Create시 값 반환
- Post Update, Create시 값 반환
=> Feature: Folder, Post 생성 

src/app.module.ts, src/modules/classification/classification.controller.ts, src/modules/classification/classification.module.ts, src/modules/classification/classification.repository.ts, src/modules/classification/classification.service.ts, src/modules/classification/docs/countClassification.docs.ts, src/modules/folders/folders.module.ts
=> Feat: Add classification count API

src/modules/folders/docs/folder-api.docs.ts, src/modules/posts/docs/createPost.docs.ts, src/modules/posts/posts.service.ts
- 오류코드 명시 유실된 부분 다시 추가
- create post시 user folder인지 validation 누락되어있어서 추가했어용
=> 오류코드 명시 유실된 부분 추가 및 create post에 validation 추가

serverless.yml
람다 타임아웃 30초로 고정
인프라 관련 세팅은 serverless에 명시하지 않으면 다음 배포시 초기화되거나 기본값으로 바뀌게 됩니당
=> chore: 람다 타임아웃 고정

.github/workflows/build.yml, src/modules/folders/folders.pg.repository.ts, src/modules/prisma/prisma.module.ts, src/modules/prisma/prisma.service.ts, src/modules/users/users.pg.repository.ts, src/modules/users/users.repository.ts, src/modules/users/users.service.ts
- User creation시 폴더 중복 생성이 되는 문제 해결이 안되어 있어서 변경했어용..!!
=> Fix: Fix duplicated folder creation

src/app.swagger.ts, src/common/utils/parser.util.ts, src/modules/folders/folders.service.ts
=> Fix: 폴더 이름 변경 및 Web Parsing Header 추가

src/modules/users/response/createUser.response.ts, src/modules/users/users.controller.ts, src/modules/users/users.service.ts
- Auth API에 토큰이랑 userId 같이 반환하도록 변경
=> Fix: Add user id to auth api

src/modules/classification/classification.repository.ts
=> chore : 나중에 읽을 폴더로 추천된 경우는 제외

src/modules/ai-classification/ai-classification.service.ts, src/modules/folders/folders.repository.ts
=> Fix: Fix ai classification logic

src/common/utils/parser.util.ts
=> Fix: Remove user-agent header

src/common/utils/parser.util.ts, src/modules/posts/docs/index.ts, src/modules/posts/docs/retrievePost.docs.ts, src/modules/posts/postKeywords.repository.ts, src/modules/posts/posts.controller.ts, src/modules/posts/posts.service.ts, src/modules/posts/response/index.ts, src/modules/posts/response/retrievePost.response.ts
=> Feat: Add retrieve single post API

src/infrastructure/ai/ai.constant.ts
gpt 모델 변경
참고 : https://context.ai/compare/gpt-4o-mini/gpt-3-5-turbo
=> gpt 모델 4o mini로 변경

pnpm-lock.yaml, src/common/utils/parser.util.ts
=> Fix: Fix redirect as manual

src/common/utils/parser.util.ts
=> Fix: Fix content parser

src/common/utils/parser.util.ts, src/modules/posts/posts.service.ts
=> Fix: Fix title to ternary operation

.github/CODEOWNERS
- Add codeowner @Ahn-seokjoo. Welcome 🎉!!
=> Welcome Seokjoo

package.json, pnpm-lock.yaml, src/infrastructure/database/database.module.ts, src/infrastructure/database/entities/ai-classification.entity.ts, src/infrastructure/database/entities/base.entity.ts, src/infrastructure/database/entities/folder.entity.ts, src/infrastructure/database/entities/keyword.entity.ts, src/infrastructure/database/entities/metrics.entity.ts, src/infrastructure/database/entities/post-keyword.entity.ts, src/infrastructure/database/entities/post.entity.ts, src/infrastructure/database/entities/user.entity.ts, src/modules/classification/classification.pg.repository.ts, src/modules/folders/folders.module.ts, src/modules/folders/folders.pg.repository.ts, src/modules/folders/folders.v2.controller.ts, src/modules/folders/folders.v2.service.ts, src/modules/keywords/keyword.pg.repository.ts, src/modules/metrics/metrics.pg.repository.ts, src/modules/posts/postKeywords.pg.repository.ts, src/modules/posts/posts.pg.repository.ts, src/modules/users/users.pg.repository.ts
=> typeorm & postgresql 세팅
